server.port=33368
spring.thymeleaf.cache=false
logging.level.helloWorldController=warn
logging.file.path=/home/ljj/jiaotou/logs
logging.file.name=/home/ljj/jiaotou/logs/toshow.log
# ====== ????? Redis ?? ======
# ????
spring.redis.host=100.65.38.141
spring.redis.port=6380
spring.redis.password=whdx123cgz666
spring.redis.database=2
spring.redis.timeout=60s

# ???????
#spring.redis.cluster.nodes=100.65.38.139:8001,100.65.38.140:8002,100.65.38.141:8003,100.65.38.142:8004,100.65.38.36:8005,100.65.38.37:8006
#spring.redis.cluster.max-redirects=3
# ====== Redis ???? ======

converter1.file=data/sx_json.json
converter2.file=data/xx_json.json
kafka.brokers=10.48.53.82:9092
kafka.topics=MergedRampPathData
spring.redis.jedis.pool.max-idle=500
spring.redis.jedis.pool.min-idle=50
spring.redis.jedis.pool.max-wait=-1s
spring.redis.jedis.pool.max-active=-1

# MergedRampPathData
# MergedPathData.special
# MergedPathData.wc
# smartBS_xg