# 应用服务 WEB 访问端口
# 100.65.38.139
server.port=33333
spring.thymeleaf.cache=false
# http://100.65.38.139:33333
spring.redis.host=100.65.38.139
spring.redis.port=6379
spring.redis.database=2
spring.redis.timeout=60s
spring.redis.password=whdx123cgz666
#spring.redis.sentinel.master=mymaster
#spring.redis.sentinel.nodes=100.65.38.139:26379,100.65.38.140:26379,100.65.38.141:26379
converter1.file=/home/ljj/sx_json.json
converter2.file=/home/ljj/xx_json.json
kafka.brokers=100.65.38.40:9092
kafka.topics=MergedPathData.sceneTest.1,MergedPathData.sceneTest.2,MergedPathData.sceneTest.3,MergedPathData.sceneTest.4,MergedPathData.sceneTest.5
spring.redis.jedis.pool.max-idle=500
spring.redis.jedis.pool.min-idle=50
spring.redis.jedis.pool.max-wait=-1s
spring.redis.jedis.pool.max-active=-1



